kumuluzee:
  name: invoice-service
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count"
  openapi:
    enabled: true
    ui:
      enabled: true
  logs:
    loggers:
      - name: ''
        level: INFO
  config:
    consul:
      agent: http://localhost:8500
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/mainDB
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  datasources:
    - jndi-name: jdbc/mainDB
      connection-url: jdbc:postgresql://localhost:5432/invoice-service
      username: postgres
      password: postgres
      pool:
        max-size: 20
  security:
    keycloak:
      json: '{
               "realm": "rso",
               "bearer-only": true,
               "auth-server-url": "https://keycloak.mjamsek.com/auth",
               "ssl-required": "external",
               "resource": "invoice-service",
               "confidential-port": 0
             }'
  rest-client:
    registrations:
      - class: order-service
        url: http://localhost:8081/v1
        read-timeout: 5000
  grpc:
    server:
      url: localhost
      http:
        port: 8443
  streaming:
    kafka:
      producer:
        bootstrap-servers: localhost:9092
        #acks: all
        #retries: 3
        #batch-size: 16384
        #linger-ms: 20
        #buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: si.rso.event.streaming.serialization.EventStreamMessageSerializer
google:
  storage:
    url: https://storage.googleapis.com
    bucket-name: rso-vaje-bucket
service-config:
  maintenance: false