apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: invoice-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: invoice-app-deployment
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: storage-upload-pass
      containers:
        - name: invoice-app-container
          image: rso6315/invoice-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: third-cluster
            - name: KUMULUZEE_SERVER_BASE-URL
              value: http://35.246.208.18/invoice-service
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_STREAMING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS
              value: kafka-service.e-store:9092
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://invoice-db.e-store:5432/invoices
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: invoice-pass
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: invoice-service
  name: invoice-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31012
      targetPort: 8080
      protocol: TCP
      name: server
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: grpc
  selector:
    app: invoice-app-deployment