language: java
dist: trusty

jdk:
- openjdk11

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true --settings .ci/settings.xml -P rso
script:
  - echo "DONE"
  # - mvn test

notifications:
  slack: rso-6315:GemkjD1zzD1AAKrXCrn9LUC3
